// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNUxuFx4g9qx0NQHy9z84ZH9jVYS913RE',
    appId: '1:672474191337:web:483ff6588f72d46037e778',
    messagingSenderId: '672474191337',
    projectId: 'portfolio-81ac3',
    authDomain: 'portfolio-81ac3.firebaseapp.com',
    storageBucket: 'portfolio-81ac3.appspot.com',
    measurementId: 'G-X2C8DTMFTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCefMnBbRtb9q0Sar3rDW932D8z_JuC9fM',
    appId: '1:672474191337:android:780543c819d44fff37e778',
    messagingSenderId: '672474191337',
    projectId: 'portfolio-81ac3',
    storageBucket: 'portfolio-81ac3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeCwbxX70sBw5_LjiDLMlM0T2IWmlxFzA',
    appId: '1:672474191337:ios:138772377714bb7f37e778',
    messagingSenderId: '672474191337',
    projectId: 'portfolio-81ac3',
    storageBucket: 'portfolio-81ac3.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeCwbxX70sBw5_LjiDLMlM0T2IWmlxFzA',
    appId: '1:672474191337:ios:138772377714bb7f37e778',
    messagingSenderId: '672474191337',
    projectId: 'portfolio-81ac3',
    storageBucket: 'portfolio-81ac3.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNUxuFx4g9qx0NQHy9z84ZH9jVYS913RE',
    appId: '1:672474191337:web:463f29a9895cdaa537e778',
    messagingSenderId: '672474191337',
    projectId: 'portfolio-81ac3',
    authDomain: 'portfolio-81ac3.firebaseapp.com',
    storageBucket: 'portfolio-81ac3.appspot.com',
    measurementId: 'G-YFW1P0XYYX',
  );

}