// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB51BcKu7MuLdjr_Wq7mfub-15rJtvXDSQ',
    appId: '1:350586222314:web:7a0a0e6b6c0729825ec993',
    messagingSenderId: '350586222314',
    projectId: 'richard-spotify-12345',
    authDomain: 'richard-spotify-12345.firebaseapp.com',
    storageBucket: 'richard-spotify-12345.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9y4qALkf0Oq-7aT-GbpQybq3ZguehfJI',
    appId: '1:350586222314:android:00da450d69edffd95ec993',
    messagingSenderId: '350586222314',
    projectId: 'richard-spotify-12345',
    storageBucket: 'richard-spotify-12345.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHTQBCvzTdtl6qI518W9W6Q1t7mjJWdLM',
    appId: '1:350586222314:ios:1c419fc33e9e2d795ec993',
    messagingSenderId: '350586222314',
    projectId: 'richard-spotify-12345',
    storageBucket: 'richard-spotify-12345.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHTQBCvzTdtl6qI518W9W6Q1t7mjJWdLM',
    appId: '1:350586222314:ios:1c419fc33e9e2d795ec993',
    messagingSenderId: '350586222314',
    projectId: 'richard-spotify-12345',
    storageBucket: 'richard-spotify-12345.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB51BcKu7MuLdjr_Wq7mfub-15rJtvXDSQ',
    appId: '1:350586222314:web:1dcceb38ae5c5e915ec993',
    messagingSenderId: '350586222314',
    projectId: 'richard-spotify-12345',
    authDomain: 'richard-spotify-12345.firebaseapp.com',
    storageBucket: 'richard-spotify-12345.appspot.com',
  );
}
